# Generated by Django 3.2.8 on 2021-11-05 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystella', '0002_auto_20211022_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='images',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='images',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='images',
            name='image4',
        ),
        migrations.AddField(
            model_name='images',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
